.setup_lib:
  before_script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - ldconfig -p | grep libgfort

py37_gcc8:
  image: python:3.7-buster
  variables:
    TARGET: mokit-master_linux_py37_gcc8
  extends: .setup_lib
  script:
    - cd lib
    - cp /usr/lib/*/libopenblasp*.so .
    - cp /usr/lib/libgfortran.so.4.* .
    - ln -s libgfortran.so.4.* libgfortran.so.4
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ../src
    - make all -f Makefile.gnu_openblas_ci
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    #- tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET/
py38_gcc8:
  image: python:3.8-buster
  variables:
    TARGET: mokit-master_linux_py38_gcc8
  extends: .setup_lib
  script:
    - cd lib
    - cp /usr/lib/*/libopenblasp*.so .
    - cp /usr/lib/libgfortran.so.4.* .
    - ln -s libgfortran.so.4.* libgfortran.so.4
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ../src
    - make all -f Makefile.gnu_openblas_ci
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    #- tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET/
  #release:
  #  name: 'MOKIT-1.2.4
py39_gcc10:
  image: python:3.9-bullseye
  variables:
    TARGET: mokit-master_linux_py39_gcc10
  extends: .setup_lib
  script:
    - cd lib
    - cp /usr/lib/*/libopenblasp*.so .
    - cp /usr/lib/libgfortran.so.5.* .
    - ln -s libgfortran.so.5.* libgfortran.so.5
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ../src
    - make all -f Makefile.gnu_openblas_ci
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    #- tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET/
py310_gcc10:
  image: python:3.10-bullseye
  variables:
    TARGET: mokit-master_linux_py310_gcc10
  extends: .setup_lib
  script:
    - cd lib
    - cp /usr/lib/*/libopenblasp*.so .
    - cp /usr/lib/libgfortran.so.5.* .
    - ln -s libgfortran.so.5.* libgfortran.so.5
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ../src
    - make all -f Makefile.gnu_openblas_ci
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    #- tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET/
