build:
  stage: build
  image: python:3.8
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
