
conda19.10_py37_gcc8:
  image: continuumio/anaconda3:2019.10
  variables:
    TARGET: mokit-master_linux_conda19.10_py37_gcc8
  script:
    - apt-get update -qy --allow-releaseinfo-change
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib/*/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz
conda20.02_py37_gcc8:
  image: continuumio/anaconda3:2020.02
  variables:
    TARGET: mokit-master_linux_conda20.02_py37_gcc8
  script:
    - apt-get update -qy --allow-releaseinfo-change
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib/*/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz
conda20.07_py38_gcc8:
  image: continuumio/anaconda3:2020.07
  variables:
    TARGET: mokit-master_linux_conda20.07_py38_gcc8
  script:
    - apt-get update -qy --allow-releaseinfo-change
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib/*/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz
conda20.11_py38_gcc8:
  image: continuumio/anaconda3:2020.11
  variables:
    TARGET: mokit-master_linux_conda20.11_py38_gcc8
  script:
    - apt-get update -qy --allow-releaseinfo-change
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib/*/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz
py37_gcc8:
  image: python:3.7-buster
  variables:
    TARGET: mokit-master_linux_py37_gcc8
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib/*/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz
py38_gcc8:
  image: python:3.8-buster
  variables:
    TARGET: mokit-master_linux_py38_gcc8
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib/*/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz
  #release:
  #  name: 'MOKIT-1.2.4
py39_gcc8:
  image: python:3.9-bullseye
  variables:
    TARGET: mokit-master_linux_py39_gcc10
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib/*/*/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz
