build:
  stage: build
  image: python:3.8
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    - pip install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ..
    - cp /usr/lib/*/*/libopenblas* lib/
    - export TARGET=mokit-master_linux_py38
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    paths:
      - ./*tar.gz
