centos7_conda20.11_py38:
  image: centos:7
  variables:
    TARGET: mokit-master_linux_centos_conda20.11_py38
  script:
    - yum install -y epel-release
    - yum install -y openblas-devel make gcc gcc-gfortran wget 
    - wget --no-check-certificate https://mirrors.bfsu.edu.cn/anaconda/archive/Anaconda3-2020.11-Linux-x86_64.sh
    - >
      { echo ${KEYCODE_ENTER};
      echo "yes";
      echo ${KEYCODE_ENTER};
      } | sh ./Anaconda3-2020.11-Linux-x86_64.sh 
    - source /root/bashrc
    - conda install numpy
    - cd src
    - make all -f Makefile.gnu_openblas
    - cd ../lib
    - cp /usr/lib64/libopenblasp*.so .
    - ln -s libopenblasp*.so libopenblas.so
    - cd ..
    - mkdir $TARGET
    - cp -r bin lib doc examples basis CHANGELOG *.md $TARGET
    - tar czvf $TARGET.tar.gz $TARGET
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET.tar.gz


