# Firstly written by Dr. Zehao Zhou, zehaozhoucase@gmail.com
# the funtion get_mf_from_gbw() is added by jxzou at 20260502


def get_mf_from_fch(fch_file: str, functional: str = None):
    '''
    convert .fch(k) file to PySCF mf object
    fch_file: fch file generated by Gaussian
    functional: functional name used in PySCF
    '''
    import numpy as np
    from pyscf import scf, dft
    from mokit.lib.gaussian import load_mol_from_fch, mo_fch2py
    from mokit.lib.rwwfn import (
        find_irel_in_fch,
        read_eigenvalues_from_fch,
        read_nbf_and_nif_from_fch,
        read_na_and_nb_from_fch,
        check_uhf_in_fch,
        get_occ_from_na_nb,
        read_charge_and_mult_from_fch
    )

    irel = find_irel_in_fch(fch_file)
    if irel not in (-1, -3):
        raise ValueError('Unsupported type of relativistic Hamiltonian.'
                         ' Only non-relativistic or sf-X2C supported.')

    mol = load_mol_from_fch(fch_file)
    print('N atoms =', mol.natm)
    #mol.build(parse_arg=False)
    # `build` is not needed since it is specifed in load_mol_from_fch

    mo_coeff = mo_fch2py(fch_file)
    nbf, nif = read_nbf_and_nif_from_fch(fch_file)
    print('nbf =', nbf)
    print('nif =', nif)

    na, nb = read_na_and_nb_from_fch(fch_file)
    if mol.nelectron != na+nb:
        print('\nIt seems that ECP/PP is used. ECP/PP data is missing when '
              'using .mkl/.molden. But this')
        print('does not affect the calculation of TDA-/TDDFT-ris energy. In'
              ' the future, we will switch')
        print('to using ORCA json in order to solve this problem.')
    print('mo_coeff.shape', mo_coeff.shape)

    uhf = check_uhf_in_fch(fch_file)
    if uhf == 1:
        mo_energy_a = read_eigenvalues_from_fch(fch_file, nif, 'a')
        mo_energy_b = read_eigenvalues_from_fch(fch_file, nif, 'b')
        mo_energy = np.stack((mo_energy_a, mo_energy_b))
        print('mo_energy.shape', mo_energy.shape)
        print('Unrestricted Kohn-Sham')
        if (nbf > nif):
            if functional == 'hf':
                old_mf = scf.UHF(mol)
            else:
                old_mf = dft.UKS(mol)
            mf = scf.remove_linear_dep_(old_mf, threshold=1e-6, lindep=1e-6)
        elif (nbf == nif):
            if functional == 'hf':
                mf = scf.UHF(mol)
            else:
                mf = dft.UKS(mol)
        else:
            raise ValueError('nbf<nif. This is impossible.')
        mf.mo_occ = np.asarray([[1] * na + [0] * (nif - na),
                                [1] * nb + [0] * (nif - nb)])
    else:
        charge, mult = read_charge_and_mult_from_fch(fch_file)
        if mult != 1:
            raise NotImplementedError('TDA-/TDDFT-ris based on ROHF/ROKS reference'
                                      ' not supported currently.')
        mo_energy = read_eigenvalues_from_fch(fch_file, nif, 'a')
        print('mo_energy.shape', mo_energy.shape)
        print('Restricted Kohn-Sham')
        if (nbf > nif):
            if functional == 'hf':
                old_mf = scf.RHF(mol)
            else:
                old_mf = dft.RKS(mol)
            mf = scf.remove_linear_dep_(old_mf, threshold=1e-6, lindep=1e-6)
        elif (nbf == nif):
            if functional == 'hf':
                mf = scf.RHF(mol)
            else:
                mf = dft.RKS(mol)
        else:
            raise ValueError('nbf<nif in '+fch_file+'. Impossible!')
        mf.mo_occ = get_occ_from_na_nb(nif, na, nb)

    mf.verbose = 4
    mf.mo_coeff = mo_coeff
    mf.mo_energy = mo_energy
    if functional != 'hf':
        mf.xc = functional
        mf.grids.atom_grid = (99,590) # mimic `int=ultrafine` of Gaussian KS-DFT
    if irel == -3:
        mf = mf.x2c1e()
    print('functional: ', functional)
    return mf

# alias
load_mf_from_fch = get_mf_from_fch


def get_mf_from_gbw(gbwname, functional, sfx2c=False):
    '''
    convert .gbw file to PySCF mf object
    A wrapper of orca_2mkl, molden2fch, get_mf_from_fch. In the future, we may
    use the .json format instead of .molden
    '''
    import os
    from mokit.lib.qchem import util_wrapper

    irel = -3 if sfx2c else -1
    proname = gbwname[0:gbwname.rindex('.gbw')]
    mklname = proname+'.mkl'
    fch_file = proname+'.fch'
    util_wrapper.gbw2mkl(gbwname)
    util_wrapper.mkl2fch_wrap(mklname, fch_file, 0, irel)
    os.remove(mklname)
    mf = get_mf_from_fch(fch_file, functional)
    os.remove(fch_file)
    return mf

# alias
load_mf_from_gbw = get_mf_from_gbw

