{% set data = load_setup_py_data() %}

package:
  name: "mokit"
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  number: 1
  string: "py{{PY_VER}}_{{PKG_HASH}}_{{PKG_BUILDNUM}}"

requirements:
  build:
    - python {{ python }}
    - make
    - mkl
    - numpy {{ numpy }}
    - {{ compiler('fortran') }}
    - libgfortran5
  run:
    - python {{ python }}
    - mkl
    - numpy {{ numpy }}
    - libgfortran5
