# written by jxzou at 20250510: a try for Intel OneAPI 2025 or higher

BIN = ../bin
LIB = ../mokit/lib

# --- ifx + Intel MKL ----
# CC=icx FC=ifx make all -f Makefile.intel_ifx

F90 = ifx
FFLAGS = -O2 -fpp -fPIC -qopenmp
MKL_FLAGS = -L$(MKLROOT)/lib/intel64 -lmkl_rt
F2PY = f2py
F2_FLAGS = --fcompiler=intelem --f90flags="-fpp -O2 -qopenmp" -I$(PWD) -liomp5

include Makefile.main
