# written by jxzou at 20200322
# updated by jxzou at 20200515: delete 'install', add $(BIN)
# updated by jxzou at 20221008: delete F2_MKL_FLAGS

BIN = ../bin
LIB = ../mokit/lib

# --- ifort + Intel MKL ----
F90 = ifort
FFLAGS = -O2 -fpp -fPIC -qopenmp -warn unused
MKL_FLAGS = -L$(MKLROOT)/lib/intel64 -lmkl_rt
F2PY = f2py
F2_FLAGS = --fcompiler=intelem --f90flags="-fpp" --opt="-O2 -qopenmp" -liomp5

include Makefile.main
