# written by wsr at 20240831: -lgomp is needed in this case

BIN = ../bin
LIB = ../mokit/lib

# --- gfortran + openblas ---
FFLAGS += -O2 -cpp -fPIC -fopenmp -fno-tree-vectorize -fno-math-errno
MKL_FLAGS = -L$(BUILD_PREFIX)/lib -lopenblas
F2PY = f2py
F2_FLAGS = --f90flags="-cpp -fopenmp -fno-tree-vectorize -fno-math-errno" -lgomp

include Makefile.main
