# written by jxzou at 20200322
# updated by jxzou at 20200515: delete 'install', add $(BIN)
# updated by jxzou at 20221008: delete F2_MKL_FLAGS
# updated by ansatzX at 202310130: support brew_openblas

BIN = ../bin
LIB = ../mokit/lib
# USE_CONDA = source $(HOMEBREW_PREFIX)/Caskroom/miniconda/base/bin/activate base 
# --- gfortran + OpenBLAS ---
F90    = gfortran
FFLAGS = -O2 -cpp -fPIC
MKL_FLAGS = -L$(HOMEBREW_PREFIX)/opt/openblas/lib  -lopenblas
F2PY   = source $(HOMEBREW_PREFIX)/Caskroom/miniconda/base/bin/activate base  && python -m numpy.f2py
F2_FLAGS = 
F2_F90_FLAGS = --f90flags="-cpp" 

include Makefile.main


