# written by jxzou at 20200322
# updated by jxzou at 20200515: delete 'install', add $(BIN)
# updated by jxzou at 20221008: delete F2_MKL_FLAGS
# updated by wsr at 20221202: adjust for gitlab ci

BIN = ../bin
LIB = ../mokit/lib

# --- gfortran + OpenBLAS ---
F90 = gfortran
FFLAGS = -O2 -cpp -fPIC -fopenmp -fno-tree-vectorize -fno-math-errno -L../lib 
MKL_FLAGS = -lopenblas
F2PY = f2py
F2_FLAGS = --f90flags="-cpp -fopenmp -fno-tree-vectorize -fno-math-errno" -lgomp

include Makefile.main
