.setup_conda:
  image:
    name: continuumio/miniconda3:latest
  before_script:
    #- apt-get update -qy
    - conda init bash
    - source ~/.bashrc
    - conda create -n mokit-build python=3.9 libgcc-ng=11
    - conda activate mokit-build
    - conda install anaconda-client conda-build setuptools_scm
    - export ANACONDA_API_TOKEN=${ANACONDA_TOKEN}
    #- ldconfig -p | grep libgfort
    #- ls /usr/lib/x86_64-linux-gnu/libopenblas* -l
    #- ls /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas* -l

.setup_cf:
  image:
    name: continuumio/miniconda3:latest
  before_script:
    #- apt-get update -qy
    - conda init bash
    - source ~/.bashrc
    - conda create -n mokit-build python=3.9 anaconda-client conda-build setuptools_scm
    - conda activate mokit-build
    - export ANACONDA_API_TOKEN=${ANACONDA_TOKEN}

conda_build:
  extends: .setup_conda
  only:
    refs:
      - master
      - distu-fix
    changes:
      - "mokit/__init__.py"
      - "conda/conda*/meta.yaml"
  script:
    #- conda build --output-folder ./output conda/conda37
    #- conda build --output-folder ./output conda/conda38p
    - conda build --output-folder ./output conda/conda39p
    - conda build --output-folder ./output conda/conda310p
    - anaconda upload ./output/linux-64/mokit*.conda --skip-existing

conda_build_test:
  extends: .setup_conda
  only:
    refs:
      - ci-update-2025
      - conda-fix-dep
      - conda-fix-glibc
      - conda-fix-gcc
      - conda-format
      - py312-conda
    changes:
      - "mokit/__init__.py"
      - "conda/conda*/meta.yaml"
  script:
    #- conda build --output-folder ./output conda/conda37
    #- conda build --output-folder ./output conda/conda38p
    - conda build --output-folder ./output conda/conda39p
    - conda build --output-folder ./output conda/conda310p
    - anaconda upload ./output/linux-64/mokit*.conda --skip-existing --label test

conda_build_cf:
  extends: .setup_cf
  only:
    refs:
      - cf
      - master
      - distu-fix
    changes:
      - "mokit/__init__.py"
      - "conda/cf*/meta.yaml"
  script:
    - conda config --set channel_priority strict
    - conda build --output-folder ./output_cf -c conda-forge conda/cf39
    #- conda build --output-folder ./output_cf -c conda-forge conda/cf310p
    - cd output_cf/linux-64
    - anaconda upload mokit*.conda --skip-existing --label cf

conda_build_cf_test:
  extends: .setup_cf
  only:
    refs:
      - cf-debug
      - ci-update-2025
      - conda-fix-glibc
      - conda-format
      - py312-conda
    changes:
      - "mokit/__init__.py"
      - "conda/cf*/meta.yaml"
  script:
    - conda config --set channel_priority strict
    - conda build --output-folder ./output_cf -c conda-forge conda/cf39
    #- conda build --output-folder ./output_cf -c conda-forge conda/cf310p
    - cd output_cf/linux-64
    - anaconda upload mokit*.conda --skip-existing --label testcf
