variables:
  OB_ROOT: /usr/lib/*
.setup_lib:
  except:
    - conda
    - newconda2
    - cf
    - distu-fix
  #only:
  #  changes:
  #    - "mokit/__init__.py"
  before_script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev make gcc gfortran  
    #- pip install numpy
    - ldconfig -p | grep libgfort
    - ls /usr/lib/x86_64-linux-gnu/libopenblas* -l
    #- ls /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas* -l
  after_script:
    - cd mokit/lib
    - cp $OB_ROOT/libopenblasp*.so .
    - cp /usr/lib/*/libgfortran.so.5.* .
    - ln -s libgfortran.so.5.* libgfortran.so.5
    - ln -s libopenblasp*.so libopenblas.so.0
    - cd ../..
    - mkdir $TARGET
    - cp -r bin mokit doc examples CHANGELOG *.md $TARGET
    - mkdir $TARGET/src
    - cp src/modify* $TARGET/src

#py37_gcc8:
#  image: python:3.7-buster
#  variables:
#    TARGET: mokit-master_linux_py37_gcc8
#  extends: .setup_lib
#  script:
#    - cd src
#    - make all -f Makefile.gnu_openblas_ci
#    - cd ..
#  artifacts:
#    name: $TARGET
#    paths:
#      - ./$TARGET/

lint:
  image: python:3.8-buster
  except:
    - cf
  script:
    - pip install flake8
    - flake8 --config .flake8 

# py38_gcc8:
#   image: python:3.8-buster
#   variables:
#     TARGET: mokit-master_linux_py38_gcc8
#   extends: .setup_lib
#   script:
#     - pip install numpy==1.21
#     - cd src
#     - make all -f Makefile.gnu_openblas_ci
#     - cd ..
#   artifacts:
#     name: $TARGET
#     paths:
#       - ./$TARGET/

py39_gcc10:
  image: python:3.9-bullseye
  variables:
    TARGET: mokit-master_linux_py39_gcc10
    OB_ROOT: /usr/lib/*/openblas-pthread
  extends: .setup_lib
  script:
    - pip install numpy==1.21
    - cd src
    - make all -f Makefile.gnu_openblas_ci
    - cd ..
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET/

py310_gcc10:
  image: python:3.10-bullseye
  variables:
    TARGET: mokit-master_linux_py310_gcc10
    OB_ROOT: /usr/lib/*/openblas-pthread
  extends: .setup_lib
  script:
    - pip install numpy==1.23
    - cd src
    - make all -f Makefile.gnu_openblas_ci
    - cd ..
  artifacts:
    name: $TARGET
    paths:
      - ./$TARGET/
