#{% set data = load_setup_py_data() %} # do not remove this line
{% set data = load_file_data('pyproject.toml') %}
{% set proj = data['project'] %}
{% set urls = data['project']['urls'] %}

package:
  name: "mokit"
  version: "{{ proj['version'] }}"

source:
  path: ../..

build:
  number: 7
  string: "py{{ PY_VER }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"

requirements:
  build:
    - python {{ python }}
    #- setuptools <=73
    - make
    - blas * *mkl*
    - mkl {{ mkl }}
    - numpy {{ numpy }}
    - {{ compiler('fortran') }}
    - libgfortran5
    - sysroot_linux-64 2.17
  run:
    - python {{ python }}
    - blas * *mkl*
    - mkl {{ mkl }}
    - numpy {{ numpy }}
    - libgfortran5

about:
  home:            "{{ urls['Homepage'] }}"
  license:         "Apache-2.0"
  summary:         "{{ proj['description'] }}"
  description:     "MOKIT offers various utilities and modules to transfer MOs among various quantum chemistry software packages.\nBesides, the automr program in MOKIT can set up and run common multi-reference calculations in a black-box way."
  dev_url:         "{{ urls['Repository'] }}"
  doc_url:         "{{ urls['Documentation'] }}"
